### ISSUE TITLE
Организации работы с файлами.

### ISSUE THREAD

**Issue by Ebisu02** [trpo2021/cw-dream_team#2]
#### 1. Реализовать функцию приложения, описанного в Техническом Задании Приложения: 
>"Если программа запущена не в настроенной директории, то программа создает начальную конфигурацию в той   директории, где находится".

#### 2.  Реализовать функцию приложения, описанного в Техническом Задании приложения:
>"После окончания создания HTML страницы она помещается во временную директорию".

#### 3.  Реализовать функцию приложения, описанного в Техническом задании приложения:
>"Раз в некоторое время программа проверяет статьи на наличие изменений и обновляет временные файлы, если что-то было изменено".

**Comment by itachiuchiha77** [comment]
true

**Comment by Ebisu02** [comment]
Дедлайн первой задачи - 28.05.2021

**Comment by Ebisu02** [comment]
Все сделано, закрываю.
